services:

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.6.1
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000

  kafka:
#    image: confluentinc/cp-kafka:7.6.1
#    depends_on:
#      - zookeeper
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
#
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
#      settings for confluent version with zooKeeper and shit
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_c_db
    ports:
      - "5432:5432"

  service-a:
    build: ./service_a
    depends_on:
      - kafka
      - mongo
    environment:
      # MongoDB
      MONGODB_URI: mongodb://mongo:27017/service-a-db

      # Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # URLs до других сервисов
      SERVICE_B_URL: http://service-b:8080
    ports:
      - "8081:8080"

  service-b:
    build: ./service_b
    depends_on:
      - redis
    environment:
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # URLs до других сервисов
      SERVICE_C_URL: http://service-c:8080
    ports:
      - "8082:8080"

  service-c:
    build: ./service_c
    depends_on:
      - postgres
      - kafka
    environment:
      # PostgreSQL
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/service_c_db
      DATASOURCE_USERNAME: user
      DATASOURCE_PASSWORD: password

      # Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8080"